# Generated by Django 4.2 on 2023-11-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=256, unique=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='ResAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='codigo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modulo')),
            ],
            options={
                'unique_together': {('modulo', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='CritEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, verbose_name='codigo')),
                ('descripcion', models.TextField()),
                ('minimo', models.BooleanField()),
                ('resultado_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resaprendizaje')),
            ],
            options={
                'unique_together': {('resultado_aprendizaje', 'codigo')},
            },
        ),
    ]
